server:
  port: 7761
spring:
  application:
    name: customer-user
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka
  instance:
    prefer-ip-address: true
provider-user2: 
  ribbon: 
   NFLoadBalancerRuleClassName: com.lbconfig.MyRule

logging:
  level: 
    com.smtmvc.api.UserService: debug
   