server:
  port: 7701


spring:
  application:
    name: service-order
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf8&useSSL=true
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance: 
    prefer-ip-address: false         
