server:
  port: 7702


spring:
  application:
    name: service-user
  
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true
    user: admin
    password: admin
    in-memory: true 
    pool:
      enabled: false
    
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka
  instance: 
    prefer-ip-address: false         
