server:
  port: 7801
spring:
  application:
    name: web-front
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka
  instance:
    prefer-ip-address: true
    

logging:
  level: 
    com.smtmvc.api.UserService: debug
    
#hystrix.command.default.execution.timeout.enabled: false