server:
  port: 7750


spring:
  application:
    name: reliable-message-service
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message?characterEncoding=utf8&useSSL=true
    username: root
    password: root
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true 
    pool:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance: 
    prefer-ip-address: false         
